version: '3.8'

services:
  db:
    container_name: postgres-nest
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5433
    restart: always